# CMake generated Testfile for 
# Source directory: /data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/matrix1
# Build directory: /data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/matrix1
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(examples/matrix1 "/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/matrix1/matrix1" "512")
set_tests_properties(examples/matrix1 PROPERTIES  COST "8.0" DEPENDS "pocl_version_check" LABELS "matrix;internal;level0;vulkan" PASS_REGULAR_EXPRESSION "OK" PROCESSORS "1" SKIP_REGULAR_EXPRESSION "SKIPPED" _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/matrix1/CMakeLists.txt;35;add_test;/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/matrix1/CMakeLists.txt;0;")
add_test(examples/matrix1_local "/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/matrix1/matrix1" "512" "-l")
set_tests_properties(examples/matrix1_local PROPERTIES  COST "8.0" DEPENDS "pocl_version_check" LABELS "matrix;internal;level0;vulkan" PASS_REGULAR_EXPRESSION "OK" PROCESSORS "1" SKIP_REGULAR_EXPRESSION "SKIPPED" _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/matrix1/CMakeLists.txt;37;add_test;/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/matrix1/CMakeLists.txt;0;")
add_test(examples/matrix1_poclbin "/data/data/com.termux/files/usr/bin/cmake" "-DCMD1=/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/bin/poclcc####-o####/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/matrix1_poclbin.bin####/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/matrix1/matrix1.cl" "-DCMD2=/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/matrix1/matrix1####256####-b####/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/matrix1_poclbin.bin" "-DCMD3=/data/data/com.termux/files/usr/bin/cmake####-E####remove####-f####/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/matrix1_poclbin.bin" "-P" "/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/cmake/multi_exec_test.cmake")
set_tests_properties(examples/matrix1_poclbin PROPERTIES  COST "8.0" DEPENDS "pocl_version_check" ENVIRONMENT "POCL_KERNEL_CACHE=0" LABELS "poclbin;internal" PASS_REGULAR_EXPRESSION "OK" PROCESSORS "1" SKIP_REGULAR_EXPRESSION "SKIPPED" _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/matrix1/CMakeLists.txt;52;add_test;/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/matrix1/CMakeLists.txt;0;")
