# CMake generated Testfile for 
# Source directory: /data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/scalarwave
# Build directory: /data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/scalarwave
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(examples/scalarwave_loopvec "/data/data/com.termux/files/usr/bin/cmake" "-Dtest_cmd=/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/scalarwave/scalarwave" "-Doutput_blessed=/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/scalarwave/scalarwave_expout.txt" "-P" "/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/cmake/run_test.cmake")
set_tests_properties(examples/scalarwave_loopvec PROPERTIES  COST "3.0" DEPENDS "pocl_version_check" ENVIRONMENT "POCL_WORK_GROUP_METHOD=loopvec" FAIL_REGULAR_EXPRESSION "FAIL" LABELS "internal;cuda;hsa-native;level0" PASS_REGULAR_EXPRESSION "OK" PROCESSORS "1" SKIP_REGULAR_EXPRESSION "SKIP" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/cmake/add_test_pocl.cmake;88;add_test;/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/scalarwave/CMakeLists.txt;37;add_test_pocl;/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/scalarwave/CMakeLists.txt;0;")
add_test(examples/scalarwave_cbs "/data/data/com.termux/files/usr/bin/cmake" "-Dtest_cmd=/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/scalarwave/scalarwave" "-Doutput_blessed=/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/scalarwave/scalarwave_expout.txt" "-P" "/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/cmake/run_test.cmake")
set_tests_properties(examples/scalarwave_cbs PROPERTIES  COST "3.0" DEPENDS "pocl_version_check" ENVIRONMENT "POCL_WORK_GROUP_METHOD=cbs" FAIL_REGULAR_EXPRESSION "FAIL" LABELS "internal;cuda;hsa-native;level0" PASS_REGULAR_EXPRESSION "OK" PROCESSORS "1" SKIP_REGULAR_EXPRESSION "SKIP" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/cmake/add_test_pocl.cmake;88;add_test;/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/scalarwave/CMakeLists.txt;37;add_test_pocl;/data/data/com.termux/files/home/assignment-3/lab/pocl/pocl_src/examples/scalarwave/CMakeLists.txt;0;")
